title: Fragmentos do Abismo RPG
description: Bem-vindo ao meu site hospedado no GitHub Pages!
baseurl: ""
url: "https://lukydnomo.github.io" # URL do site
theme: minima # Exemplo de tema padrão do GitHub Pages
permalink: pretty
